### ISSUE TITLE
0.4.0 - developer tools opens another window

### ISSUE THREAD

**Issue by tinnus-napbus** [latter-bolden/port#17]
when I open developer tools via the bottom-right button it simultaneously opens them in the current window and also in another window. When I then close the second window and close the developer tools in the first, the bottom-right button no longer works to open them again. I can still open them via the drop down menu though, and this second time it doesn't open another window, only pops them out in the current one as it should.

![2021-04-18_04h01m47s](https://user-images.githubusercontent.com/77721746/115119272-a47a0580-9ffb-11eb-857a-e3b3bcf8ee7e.png)

arch linux with i3 window manager

**Comment by arthyn** [comment]
Well this one is intentional. Both dev tools are needed because taisho is split into two windows so that the main window thread stays free not blocking the UI, while the background can process tasks. 

I think the state management of the closing could be better when using the close buttons vs just clicking the bug again.
